# Generated by Django 4.2 on 2023-04-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Subjects",
            new_name="Group",
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["name"]},
        ),
        migrations.RenameModel(
            old_name="Students",
            new_name="Student",
        ),
        migrations.RenameModel(
            old_name="Groups",
            new_name="Subject",
        ),
        migrations.DeleteModel(
            name="Marks",
        ),
        migrations.AddField(
            model_name="mark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.student"
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.subject"
            ),
        ),
    ]
